/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package netvince.diyatahotel.admin;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Curtis
 */
public class Frame_employeeApply extends javax.swing.JFrame {
    /**
     * Creates new form admin_dash
     */
    public Frame_employeeApply() {
        initComponents();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        phone = new javax.swing.JTextField();
        position = new javax.swing.JTextField();
        dept = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Dashboard");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 800));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(153, 255, 255));
        jLabel1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Form");
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(100, 30, 580, 100);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setFont(new java.awt.Font("Imprint MT Shadow", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("RETURN");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(310, 660, 160, 70);

        jPanel3.setBackground(new java.awt.Color(153, 255, 255));
        jPanel3.setLayout(null);

        fname.setBackground(new java.awt.Color(0, 204, 204));
        fname.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        fname.setForeground(new java.awt.Color(0, 0, 0));
        fname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        fname.setText("First Name");
        fname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnameFocusLost(evt);
            }
        });
        jPanel3.add(fname);
        fname.setBounds(60, 30, 230, 50);

        lname.setBackground(new java.awt.Color(0, 204, 204));
        lname.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        lname.setForeground(new java.awt.Color(0, 0, 0));
        lname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lname.setText("Last Name");
        lname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnameFocusLost(evt);
            }
        });
        jPanel3.add(lname);
        lname.setBounds(330, 30, 230, 50);

        email.setBackground(new java.awt.Color(0, 204, 204));
        email.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        email.setForeground(new java.awt.Color(0, 0, 0));
        email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        email.setText("Email");
        email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFocusLost(evt);
            }
        });
        jPanel3.add(email);
        email.setBounds(60, 110, 230, 50);

        address.setColumns(20);
        address.setFont(new java.awt.Font("Imprint MT Shadow", 0, 18)); // NOI18N
        address.setLineWrap(true);
        address.setRows(5);
        address.setText("Address");
        address.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(address);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(60, 270, 500, 100);

        phone.setBackground(new java.awt.Color(0, 204, 204));
        phone.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        phone.setForeground(new java.awt.Color(0, 0, 0));
        phone.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phone.setText("Phone Number");
        phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phoneFocusLost(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
        });
        jPanel3.add(phone);
        phone.setBounds(60, 190, 230, 50);

        position.setBackground(new java.awt.Color(0, 204, 204));
        position.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        position.setForeground(new java.awt.Color(0, 0, 0));
        position.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        position.setText("Position");
        position.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                positionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                positionFocusLost(evt);
            }
        });
        jPanel3.add(position);
        position.setBounds(330, 110, 230, 50);

        dept.setBackground(new java.awt.Color(0, 204, 204));
        dept.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        dept.setForeground(new java.awt.Color(0, 0, 0));
        dept.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dept.setText("Department");
        dept.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deptFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                deptFocusLost(evt);
            }
        });
        jPanel3.add(dept);
        dept.setBounds(330, 190, 230, 50);

        jButton2.setBackground(new java.awt.Color(0, 204, 204));
        jButton2.setFont(new java.awt.Font("Imprint MT Shadow", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("REGISTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(180, 390, 230, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(90, 170, 600, 470);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Are you sure you want to return? Fill-up data will be lost.", "Returning to dashboard.", JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION){
            new Dash_admin().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String name1 = fname.getText();
        String name2 = lname.getText();
        String em = email.getText();
        String add = address.getText();
        String phonenum = phone.getText();
        String pos = position.getText();
        String department = dept.getText();
        if(name1.equals("First Name")
        ||name2.equals("Last Name")
        ||email.equals("Email")
        ||add.equals("Address")
        ||phonenum.equals("Phone")
        ||pos.equals("Position")
        ||department.equals("Department")){
            JOptionPane.showMessageDialog(null, "Please fill in all the fields","Invalid Input",DO_NOTHING_ON_CLOSE);
        }
        else if(!name1.equals("First Name")
            ||!name2.equals("Last Name")
            ||!em.equals("Email")
            ||!add.equals("Address")
            ||!phonenum.equals("Phone")
            ||!pos.equals("Position")
            ||!department.equals("Department")){
            int confirmation = JOptionPane.showConfirmDialog(null, "Are you sure you want to register this employee?", "Confirmation", JOptionPane.YES_NO_OPTION);
            if (confirmation == JOptionPane.YES_OPTION) {
                JTextField usernameField = new JTextField();
                JPasswordField passwordField = new JPasswordField();
                Object[] message = {"Admin Username:", usernameField,"Admin Password:", passwordField};
                int adminConfirm = JOptionPane.showConfirmDialog(null, message, "Admin Authentication", JOptionPane.OK_CANCEL_OPTION);
                if (adminConfirm == JOptionPane.OK_OPTION) {
                    String adminUsername = usernameField.getText();
                    String adminPassword = new String(passwordField.getPassword());
                    if (adminUsername.equals(netvince.diyatahotel.Frame_login.superuser) && adminPassword.equals(netvince.diyatahotel.Frame_login.superpass)) {
                        try {
                        Connection connection = netvince.diyatahotel.connect.getConnection();
                        PreparedStatement preparedStatement1 = connection.prepareStatement("SELECT COUNT(*) AS rowCount FROM `employee table`");
                        ResultSet resultSet = preparedStatement1.executeQuery();
                            while(resultSet.next()){
                            int rowCount = resultSet.getInt("rowCount");
                            PreparedStatement preparedStatement = connection.prepareStatement(
                            "INSERT INTO `employee table`(`employee_id`, `employee_firstname`, `employee_lastname`, `employee_email`, `employee_address`, `employee_phone`, `employee_position`, `employee_department`) "
                            + "VALUES (?,?,?,?,?,?,?,?)");
                            preparedStatement.setInt(1,rowCount + 1);
                            preparedStatement.setString(2,name1);
                            preparedStatement.setString(3,name2);
                            preparedStatement.setString(4,em);
                            preparedStatement.setString(5,add);
                            preparedStatement.setString(6,phonenum);
                            preparedStatement.setString(7,pos);
                            preparedStatement.setString(8,department);
                            preparedStatement.executeUpdate();
                            preparedStatement.close();
                            connection.close();
                            dispose();
                            new Frame_employeeList().setVisible(true);
                            }
                        }
                        catch (SQLException e) {
                        e.printStackTrace();
                        }
                    }
                    else {
                        JOptionPane.showMessageDialog(null, "Invalid admin credentials. Employee application cancelled.");
                    }
                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void fnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusGained
        // TODO add your handling code here:
        if(fname.getText().equals("First Name")){
        fname.setText("");    
        }
    }//GEN-LAST:event_fnameFocusGained

    private void fnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnameFocusLost
        // TODO add your handling code here:
        if(fname.getText().isEmpty()){
            fname.setText("First Name");
        }
    }//GEN-LAST:event_fnameFocusLost

    private void lnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusGained
        // TODO add your handling code here:
        if(lname.getText().equals("Last Name")){
        lname.setText("");    
        }
    }//GEN-LAST:event_lnameFocusGained

    private void lnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnameFocusLost
        // TODO add your handling code here:
        if(lname.getText().isEmpty()){
            lname.setText("Last Name");
        }
    }//GEN-LAST:event_lnameFocusLost

    private void emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusGained
        // TODO add your handling code here:
        if(email.getText().equals("Email")){
        email.setText("");    
        }
    }//GEN-LAST:event_emailFocusGained

    private void emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFocusLost
        // TODO add your handling code here:
        if(email.getText().isEmpty()){
            email.setText("Email");
        }
    }//GEN-LAST:event_emailFocusLost

    private void positionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_positionFocusGained
        // TODO add your handling code here:
        if(position.getText().equals("Position")){
        position.setText("");    
        }
    }//GEN-LAST:event_positionFocusGained

    private void positionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_positionFocusLost
        // TODO add your handling code here:
        if(position.getText().isEmpty()){
            position.setText("Position");
        }
    }//GEN-LAST:event_positionFocusLost

    private void phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusGained
        // TODO add your handling code here:
        if(phone.getText().equals("Phone Number")){
        phone.setText("+63 9");
        }
    }//GEN-LAST:event_phoneFocusGained

    private void phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFocusLost
        // TODO add your handling code here:
        if(phone.getText().equals("+63 9")){
            phone.setText("Phone Number");
        }
        else if(phone.getText().isEmpty()){
            phone.setText("Phone Number");
        }
    }//GEN-LAST:event_phoneFocusLost

    private void deptFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deptFocusGained
        // TODO add your handling code here:
        if(dept.getText().equals("Department")){
        dept.setText("");    
        }
    }//GEN-LAST:event_deptFocusGained

    private void deptFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deptFocusLost
        // TODO add your handling code here:
        if(dept.getText().isEmpty()){
            dept.setText("Department");
        }
    }//GEN-LAST:event_deptFocusLost

    private void addressFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusGained
        // TODO add your handling code here:
        if(address.getText().equals("Address")){
        address.setText("");    
        }
    }//GEN-LAST:event_addressFocusGained

    private void addressFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFocusLost
        // TODO add your handling code here:
        if(address.getText().isEmpty()){
            address.setText("Address");
        }
    }//GEN-LAST:event_addressFocusLost

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed
        // TODO add your handling code here:
        String pn = phone.getText();
        int l = pn.length();
        char c = evt.getKeyChar();
        if(Character.isDigit(c)){
            if(l<14){
                phone.setEditable(true);
            }
            else{
                phone.setEditable(false);
            }
        }
        else{
            if(Character.isISOControl(c)){
                phone.setEditable(true);
            }
            else{
                phone.setEditable(false);
            }
        }
    }//GEN-LAST:event_phoneKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_employeeApply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_employeeApply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_employeeApply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_employeeApply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_employeeApply().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JTextField dept;
    private javax.swing.JTextField email;
    private javax.swing.JTextField fname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField position;
    // End of variables declaration//GEN-END:variables
}
