/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package netvince.diyatahotel.reception;

import javax.swing.JOptionPane;
import netvince.diyatahotel.Frame_login;
import netvince.diyatahotel.Frame_login;

/**
 *
 * @author Curtis
 */
public class Dash_reception extends javax.swing.JFrame {

    /**
     * Creates new form reception_dash
     */
    public Dash_reception() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        checkin = new javax.swing.JButton();
        checkout = new javax.swing.JButton();
        room1 = new javax.swing.JButton();
        room = new javax.swing.JButton();
        loyalty = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receptionist Dashboard");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Receptionist Dashboard");
        jLabel2.setToolTipText("");
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 100);

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("LOGOUT");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 540, 170, 50);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(null);

        checkin.setBackground(new java.awt.Color(255, 204, 204));
        checkin.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        checkin.setForeground(new java.awt.Color(0, 0, 0));
        checkin.setText("Guest Check In");
        checkin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkinActionPerformed(evt);
            }
        });
        jPanel2.add(checkin);
        checkin.setBounds(0, 0, 230, 100);

        checkout.setBackground(new java.awt.Color(255, 204, 204));
        checkout.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        checkout.setForeground(new java.awt.Color(0, 0, 0));
        checkout.setText("Guest Check Out");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });
        jPanel2.add(checkout);
        checkout.setBounds(230, 0, 230, 100);

        room1.setBackground(new java.awt.Color(255, 204, 204));
        room1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        room1.setForeground(new java.awt.Color(0, 0, 0));
        room1.setText("Reservation");
        room1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                room1ActionPerformed(evt);
            }
        });
        jPanel2.add(room1);
        room1.setBounds(0, 100, 230, 100);

        room.setBackground(new java.awt.Color(255, 204, 204));
        room.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        room.setForeground(new java.awt.Color(0, 0, 0));
        room.setText("Housekeeping");
        room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomActionPerformed(evt);
            }
        });
        jPanel2.add(room);
        room.setBounds(230, 100, 230, 100);

        loyalty.setBackground(new java.awt.Color(255, 204, 204));
        loyalty.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        loyalty.setForeground(new java.awt.Color(0, 0, 0));
        loyalty.setText("Guest Loyalty");
        loyalty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loyaltyActionPerformed(evt);
            }
        });
        jPanel2.add(loyalty);
        loyalty.setBounds(0, 200, 460, 100);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(120, 170, 460, 300);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dashboard.jpg"))); // NOI18N
        jLabel3.setRequestFocusEnabled(false);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 80, 700, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null,"Are you sure you want to logout?", "Logging out", JOptionPane.YES_NO_OPTION);
        if(a==JOptionPane.YES_OPTION){
        new Frame_login().setVisible(true);
        dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void loyaltyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loyaltyActionPerformed
        // TODO add your handling code here:
        new Frame_loyalty().setVisible(true);
        dispose();
    }//GEN-LAST:event_loyaltyActionPerformed

    private void checkinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkinActionPerformed
        // TODO add your handling code here:
        new Frame_checkin().setVisible(true);
        dispose();
    }//GEN-LAST:event_checkinActionPerformed

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        // TODO add your handling code here:
        new Frame_checkout().setVisible(true);
        dispose();
    }//GEN-LAST:event_checkoutActionPerformed

    private void roomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomActionPerformed
        // TODO add your handling code here:
        new Frame_room().setVisible(true);
        dispose();
    }//GEN-LAST:event_roomActionPerformed

    private void room1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_room1ActionPerformed
        // TODO add your handling code here:
        new Frame_reserve().setVisible(true);
        dispose();
    }//GEN-LAST:event_room1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkin;
    private javax.swing.JButton checkout;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loyalty;
    private javax.swing.JButton room;
    private javax.swing.JButton room1;
    // End of variables declaration//GEN-END:variables
}
